site_name: Roman Knopp • Data Science Portfolio
site_description: Live notebooks, demo Streamlit i projekty end-to-end
site_url: https://romi-2023.github.io/knopp_roman_portfolio/
site_author: Roman Knopp

repo_url: https://github.com/Romi-2023/knopp_roman_portfolio
repo_name: GitHub

docs_dir: docs
use_directory_urls: true

theme:
  name: material
  language: pl
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: blue
      accent: indigo

extra_css:
  - assets/extra.css

plugins:
  - search
  - mkdocs-jupyter:
      include: ["**/*.ipynb"]
      execute: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed


nav:
  - Start: index.md
  - Projekty:
      - Iris: iris/index.md
      - Titanic: titanic/index.md
      - Półmaraton Wrocław: halfmarathon_analysis/index.md
      - Welcome Survey:
          - Opis: welcome_survey/index.md
          - Notebook: welcome_survey/research.ipynb
      - Race Analyzer: race_analyzer/index.md
      - Redstone DDD Map: redstone_ddd_map/index.md
  - Trwające:
      - Find Friends With Hobbies: ongoing/find_friends_with_hobbies/index.md
      - Data4Kids: ongoing/data4kids/index.md
  - O mnie: about/index.md
  


